blank_issues_enabled: false
contact_links:
  - name: SFF Wheel Warehouse Community
    url: https://www.facebook.com/groups/sffwheelwarehouse
    about: Join our Facebook community to ask questions and connect with other skaters
  - name: Quick Question or General Discussion
    url: https://github.com/PeachPaulison/SFF_Wheel_Library/discussions
    about: For questions, ideas, or general discussions that aren't bugs or feature requests
  - name: Documentation
    url: https://github.com/PeachPaulison/SFF_Wheel_Library/blob/main/README.md
    about: Read the README for app usage instructions and troubleshooting tips
